# Logistics

**Learning outcome**

Students that complete this course should be able to:

- Tell a story with data.
- Independently implement a workflow with large geographic and environmental data in R.
- Perform suitable data processing, visualizing, and modelling steps to support data interpretation and communication.
- Manage analysis code for long-term reproducibility.

## General information

- *Lead*: Prof. Benjamin Stocker; *Assistance*: Dr. Laura Marqués, Pepa Arán. - Geocomputation and Earth Observation group, GIUB, UniBe.
- The course language is English.
- Classes will take place on Wednesdays 16.15 - 18.00. This is our presence time, use it for your communication with us. 
- There will not be a presence check. Nevertheless, in class you will have the opportunity to ask for help with your project hiccups and exchange ideas with other students. Attending the presentation and feedback sessions will be helpful to submit a successful project by the end of the seminar.
- Maximum capacity: 30 students.
- No email communication. Use your in person time.
- Students are expected to master contents taught in *480094 Applied Geodata Science I*. The concepts of this course will be used throughout the projects of the AGDS Proseminar, from coding and using git to data wrangling and analysis.
- You will work on your own laptops, bring them to class.

## Course structure

- In groups of two, you will develop a data-intensive project. You will follow a reproducible workflow and the methods introduced in AGDS I. Familiarize yourself with the content in the [AGDS I book](https://geco-bern.github.io/agds/).
- The project should relate to research and data in Geography and Climate Science.
- Open data should be used and at least two data types combined for the analysis.
- A set of example questions and data will be provided. Groups that decide to work on those will be able to start implementing the project earlier, therefore will also have earlier presentation dates.
- You should review the code from a group other than your own, try to run their code and provide them with feedback on the implementation and the project content itself. At the same time, you will receive feedback from another group, that you should implement in your own project.
- Active participation in the presentation sessions is expected, posing questions and providing feedback for a group's presentation.

**Project scope**

Your project must contain the following:

- Answer a question or verify a pattern in climate that you have studied or heard of (e.g. where warming is happening faster), all using data.
- Reason why your question/pattern is relevant and back up your hypothesis with theory.
- Combine at least two data sources for analysis.
- Both a visualisation and a modelling component.
- Expand data sources (outside of FLUXNET data from AGDS I). We provide a list of important data sources.
- Document the whole processing and analysis of the data, from data download to result interpretations. 
- Organize your code and data into a repository (with version control), that other students can easily reproduce. You will actually run each other's code, so make it understandable.
- Present your work with slides. Each group will have 10min for their presentation, followed by 5 min for a question round.

## Schedule

There will be in total 14 sessions, scheduled as follows:

**Sessions 1-4** - Project scoping

- *Session 1 (20.09):* Course logistics. Introduction of the example project. Forming project groups. Checkpoint R installations and GitHub repository.

> Before class, follow the instructions in the first chapter of the [AGDS I book](https://geco-bern.github.io/agds/) to make sure that all the software needed for this course is installed and running. We will offer support in class, for those that encounter problems.

- *Session 2 (27.09)*: Introduction of public datasets and project ideas. Short tutorial on raster data.
- *Session 3 (04.10)*: Work on the project proposal in class and get feedback. Initial proposal due 24h after session 3 (Thursday 6pm).
- *Session 4 (11.10)*: Receive feedback from initial proposal and implement changes. Final proposal due after session 4 (Thursday 6pm).

**Sessions 5-9** - Project implementation

- *Session 5 (17.10)*: Presentation slot allocation. Project implementation. 
- *Session 6 (25.10)*: Project implementation.
- *Session 7 (01.11)*: Project implementation.
- *Session 8 (08.11)*: Project implementation.
- *Session 9 (15.11)*: Project implementation. Groups 1-3 exchange code with each other for feedback.

**Sessions 10-14** - Presentations

- *Session 10 (22.11)*: First half - Project implementation. Groups 4-6 exchange code with each other for feedback. Second half - Presentations of groups 1-3.
- *Session 11 (29.11)*: Presentations of groups 4-6. Groups 7-9 exchange code with each other for feedback.
- S*ession 12 (06.12)*: Presentations of groups 7-9. Groups 10-12 exchange code with each other for feedback.
- *Session 13 (13.12)*: Presentations of groups 10-12. Groups 13-15 exchange code with each other for feedback.
- *Session 14 (20.12)*: Presentations of groups 13-15.



## Evaluation

Evaluation will happen in the form of a report, followed by a presentation. Each pair of students will create a project and submit a GitHub repository, following the [AGDS example project](https://github.com/pepaaran/agds_proseminar_example), with all their code and a R Markdown as report. At the end of the semester, each pair will present their project to the rest of the class and exchange feedback. 

- They should find recent literature that exemplifies why their question is relevant.
