---
title: "Suggested project topics"
format: html
editor: visual
---

Here we list some ideas for your Proseminar in Geocomputation and Earth Observation projects: questions to be answered and patterns to be verified with data. These are suggestions for project proposals, which you can work on directly or take as inspiration to define your own. Naturally, this list is not exhaustive and we encourage you to come up with a project that truly peeks your interest. The datasets listed below serve just a starting point and you may need to gather more data for your project implementation.

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Project                                                                                                                                                                                                   | Datasets                                                                                                                                                       |
+===========================================================================================================================================================================================================+================================================================================================================================================================+
| **Demo:** [Spatio-temporal downscaling of temperature and VPD](https://github.com/pepaaran/agds_proseminar_example)\                                                                                      | WATCH-WFDEI                                                                                                                                                    |
|                                                                                                                                                                                                           |                                                                                                                                                                |
|                                                                                                                                                                                                           | WorldClim                                                                                                                                                      |
|                                                                                                                                                                                                           |                                                                                                                                                                |
|                                                                                                                                                                                                           | FLUXNET2015                                                                                                                                                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Homogenized time series of global mean CO2 and temperature, from the Pleistocene to 2100.                                                                                                                 | Mauna Loa CO2 trends                                                                                                                                           |
|                                                                                                                                                                                                           |                                                                                                                                                                |
|                                                                                                                                                                                                           | Corrected EPICA Dome C CO2 record (Bereiter et al. 2015)                                                                                                       |
|                                                                                                                                                                                                           |                                                                                                                                                                |
|                                                                                                                                                                                                           | RCP standard forcing                                                                                                                                           |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Relationship between vegetation height and topography                                                                                                                                                     | Global Tree Heigh (Simard et al.)                                                                                                                              |
|                                                                                                                                                                                                           |                                                                                                                                                                |
|                                                                                                                                                                                                           | Global Topographic Index                                                                                                                                       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Relationship between growing season length and vegetation biomass                                                                                                                                         | Global Above-ground Biomass (Liu et al. 2015)                                                                                                                  |
|                                                                                                                                                                                                           |                                                                                                                                                                |
|                                                                                                                                                                                                           | Climate Change Initiative Biomass                                                                                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Latitudinal gradients of the CO2 seasonal amplitude                                                                                                                                                       | In-Situ Measurements from Carbon Cycle Greenhouse Gases                                                                                                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Global patterns in the difference between land surface and air temperatures                                                                                                                               | Global Land Surface and Air Temperature (ICDC)                                                                                                                 |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Study of soil-climate relationships                                                                                                                                                                       | WorldClim\                                                                                                                                                     |
|                                                                                                                                                                                                           | \                                                                                                                                                              |
|                                                                                                                                                                                                           | SoilGrids\                                                                                                                                                     |
|                                                                                                                                                                                                           | \                                                                                                                                                              |
|                                                                                                                                                                                                           | Regridded HWSD                                                                                                                                                 |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Current analogue places for the future (2100) climate of Bern, under various emission scenarios                                                                                                           | CMIP6 climate projections                                                                                                                                      |
|                                                                                                                                                                                                           |                                                                                                                                                                |
|                                                                                                                                                                                                           | Copernicus                                                                                                                                                     |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Trends in the longest rain-free period per year, in a specific location (e.g. Bern)                                                                                                                       | rnoaa R package                                                                                                                                                |
|                                                                                                                                                                                                           |                                                                                                                                                                |
|                                                                                                                                                                                                           | MeteoSchweiz [online GUI](https://www.meteoschweiz.admin.ch/service-und-publikationen/applikationen/messwerte-und-messnetze.html#param=messnetz-klima&lang=de) |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Data imputation in the global forest age dataset for missing values in Australia                                                                                                                          | Global Forest Age Dataset                                                                                                                                      |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Correlation of runoff coefficient (Q/P) and global topographic index and/or soil data                                                                                                                     | G-RUN: Global Runoff Reconstruction\                                                                                                                           |
|                                                                                                                                                                                                           | \                                                                                                                                                              |
|                                                                                                                                                                                                           | Global Topographic Index\                                                                                                                                      |
|                                                                                                                                                                                                           | \                                                                                                                                                              |
|                                                                                                                                                                                                           | SoilGrids                                                                                                                                                      |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Prediction of future Köppen-Geiger climate classification map based on future climate (2100) and comparison of a deterministic classification implementation and a modeling approach that approximates it | CMIP6                                                                                                                                                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Comparison of biomass storage in protected areas and outside, within similar climates                                                                                                                     | Global above-ground biomass carbon\                                                                                                                            |
|                                                                                                                                                                                                           | \                                                                                                                                                              |
|                                                                                                                                                                                                           | World Database on Protected Areas                                                                                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Patterns in irrigation areas and land surface temperature                                                                                                                                                 | Global map of Irrigation Areas\                                                                                                                                |
|                                                                                                                                                                                                           | \                                                                                                                                                              |
|                                                                                                                                                                                                           | Global Land Surface Temperature (IDCD)                                                                                                                         |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Obtention of Budyko curve (AET/P vs. PET/P), using gridded data and catchment and/or surface characteristics                                                                                              | GLEAM\                                                                                                                                                         |
|                                                                                                                                                                                                           | \                                                                                                                                                              |
|                                                                                                                                                                                                           | HydroBASINS                                                                                                                                                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                           |                                                                                                                                                                |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Examples for project proposals
