# Resources

Here we list some resources that will be useful to successfully participate in the AGDS Proseminar.

## Essentials of Applied Geodata Science I {#sec-agds}

We encourage you to review some content in the [book](https://geco-bern.github.io/agds/) used during the AGDS I course, especially to freshen up knowledge on good coding practices and project management, before you start implementing your Proseminar project. The most relevant chapters and topics include:

-   [Chapter 1: Getting started.](https://geco-bern.github.io/agds/gettingstarted.html) Introduction to working with R and RStudio, including the necessary installations. Brief explanations of R projects, workspace management and git.

-   [Chapter 2: Programming primers](https://geco-bern.github.io/agds/programmingprimers.html). Basic programming concepts with R, coding style and where to find help.

-   [Chapter 6: Open science practices.](https://geco-bern.github.io/agds/openscience.html#openscience) Techniques used to facilitate reproducibility of your project.

-   [Chapter 7: Code management.](https://geco-bern.github.io/agds/codemgmt.html) Tutorial on version control using git, and how to collaborate of coding projects.

The remaining chapters of the book focus more on the data wrangling and analysis. We encourage you to go back to those for consultation, whenever you need them for your implementation.

## Handful of Pixels

The [Handful of Pixels book](https://geco-bern.github.io/handfull_of_pixels/) covers a wide range of topics, from phenology to land cover classification, using a reduced amount of data (just a handful of pixels). Most relevant for the AGDS Proseminar are:

-   [Crash course on R](https://geco-bern.github.io/handfull_of_pixels/basic_R.html). From project management to tidy data, it's a condensed version of some AGDS I chapters.
-   [Roadmap to finding good data online](https://geco-bern.github.io/handfull_of_pixels/gathering_data.html), listing open source data repositories and guidelines to check the quality of data sources.
-   [Tutorial on geospatial data in R](https://geco-bern.github.io/handfull_of_pixels/geospatial_R.html). This teaches important skills that were not covered in AGDS I, but will be used in most Proseminar projects. It includes very useful information on reading several types of geospatial data (raster and shape files), performing operations and plotting, with examples with the most used R packages.
